[technote]
id = "SQR-000"
series_id = "SQR"
canonical_url = "https://sqr-000.lsst.io/"
doi = "10.5281/zenodo.10385499"
github_url = "https://github.com/lsst-sqre/sqr-000"
github_default_branch = "main"
date_created = 2015-11-18
date_updated = 2015-11-25
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[[technote.authors]]
name = {given = "Jonathan", family = "Sick"}
internal_id = "sickj"
orcid = "https://orcid.org/0000-0003-3001-676X"
[[technote.authors.affiliations]]
name = "Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"

[technote.sphinx.linkcheck]
ignore = [
    '^https://github.com/lsst-sqre/lsst-technote-bootstrap'
]
